import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Sidebar from "../components/sidebar/sidebar"
import FollowBar from '@/components/follow-bar'
import AuthModal from '@/components/modals/auth-modal'
import ToasterProvider from '@/providers/toast-provider'
import AuthContext from '@/providers/auth-provider'
import TweetModal from '@/components/modals/tweet-modal'



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContext>

          <div className='h-full w-full grid grid-cols-12'>
            <ToasterProvider />
            <AuthModal />
            <TweetModal/>
            <Sidebar />
            {children}
            <FollowBar />
          </div>
        </AuthContext>

      </body>
    </html>
  )
}
